/*
==============================================================================
KratosStructuralApplication
A library based on:
Kratos
A General Purpose Software for Multi-Physics Finite Element Analysis
Version 1.0 (Released on march 05, 2007).

Copyright 2007
Pooyan Dadvand, Riccardo Rossi, Janosch Stascheit, Felix Nagel
pooyan@cimne.upc.edu
rrossi@cimne.upc.edu
janosch.stascheit@rub.de
nagel@sd.rub.de
- CIMNE (International Center for Numerical Methods in Engineering),
Gran Capita' s/n, 08034 Barcelona, Spain
- Ruhr-University Bochum, Institute for Structural Mechanics, Germany


Permission is hereby granted, free  of charge, to any person obtaining
a  copy  of this  software  and  associated  documentation files  (the
"Software"), to  deal in  the Software without  restriction, including
without limitation  the rights to  use, copy, modify,  merge, publish,
distribute,  sublicense and/or  sell copies  of the  Software,  and to
permit persons to whom the Software  is furnished to do so, subject to
the following condition:

Distribution of this code for  any  commercial purpose  is permissible
ONLY BY DIRECT ARRANGEMENT WITH THE COPYRIGHT OWNERS.

The  above  copyright  notice  and  this permission  notice  shall  be
included in all copies or substantial portions of the Software.

THE  SOFTWARE IS  PROVIDED  "AS  IS", WITHOUT  WARRANTY  OF ANY  KIND,
EXPRESS OR  IMPLIED, INCLUDING  BUT NOT LIMITED  TO THE  WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT  SHALL THE AUTHORS OR COPYRIGHT HOLDERS  BE LIABLE FOR ANY
CLAIM, DAMAGES OR  OTHER LIABILITY, WHETHER IN AN  ACTION OF CONTRACT,
TORT  OR OTHERWISE, ARISING  FROM, OUT  OF OR  IN CONNECTION  WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

==============================================================================
*/

//
//   Project Name:        Kratos
//   Last modified by:    $Author: virginia $
//   Date:                $Date: 2009-01-23 14:39:59 $
//   Revision:            $Revision: 1.17 $
//
//

// System includes

#if defined(KRATOS_PYTHON)

// External includes


// Project includes
#include "includes/define_python.h"
#include "structural_application.h"
#include "structural_application_variables.h"
#include "custom_python/add_custom_strategies_to_python.h"
#include "custom_python/add_constitutive_laws_to_python.h"
#include "custom_python/add_phase_laws_to_python.h"
#include "custom_python/add_custom_utilities_to_python.h"
#include "custom_python/add_custom_io_to_python.h"
#include "custom_python/add_elements_to_python.h"
#include "custom_python/add_conditions_to_python.h"
#include "custom_python/add_custom_processes_to_python.h"

namespace Kratos
{

namespace Python
{

BOOST_PYTHON_MODULE( KratosStructuralApplication )
{
    using namespace boost::python;

    class_ < KratosStructuralApplication,
           KratosStructuralApplication::Pointer,
           bases<KratosApplication>, boost::noncopyable > ( "KratosStructuralApplication" )
           ;

    AddCustomStrategiesToPython();
    AddCustomComplexStrategiesToPython();
    AddConstitutiveLawsToPython();
    AddPhaseLawsToPython();
    AddCustomUtilitiesToPython();
    AddCustomIOToPython();
    AddCustomElementsToPython();
    AddCustomConditionsToPython();
    AddCustomProcessesToPython();

    //registering variables in python

    #ifdef SD_APP_FORWARD_COMPATIBILITY
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ALPHA )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( KAPPA )
    #endif

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DAMAGE_E0 )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DAMAGE_EF )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( MATRIX_A )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( MATRIX_B )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( MATRIX_D )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( COMPOSITE_DIRECTION )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( JOINT_STIFFNESS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LINING_JOINT_STIFFNESS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( GEOMETRIC_STIFFNESS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CONTACT_PENETRATION )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( COORDINATES )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( FLUID_FLOWS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( EXCESS_PORE_WATER_PRESSURE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PRESSURE_P )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PRESSURE_Q )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( AREA )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CROSS_AREA )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( AREA_X )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( AREA_Y )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( AREA_Z )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LOCAL_INERTIA )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( INERTIA_X )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( INERTIA_Y )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( INERTIA_Z )

    //KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(VAUX)
    // KRATOS_REGISTER_IN_PYTHON_VARIABLE( WRINKLING_APPROACH )
    // KRATOS_REGISTER_IN_PYTHON_VARIABLE( GREEN_LAGRANGE_STRAIN_TENSOR )
    // KRATOS_REGISTER_IN_PYTHON_VARIABLE( PK2_STRESS_TENSOR )
    // KRATOS_REGISTER_IN_PYTHON_VARIABLE( AUXILIARY_MATRIX_1 )
    // KRATOS_REGISTER_IN_PYTHON_VARIABLE( YOUNG_MODULUS )
    // KRATOS_REGISTER_IN_PYTHON_VARIABLE( POISSON_RATIO )
    // KRATOS_REGISTER_IN_PYTHON_VARIABLE( MU )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( RETRACTION_TIME )
    // KRATOS_REGISTER_IN_PYTHON_VARIABLE( THICKNESS )
    // KRATOS_REGISTER_IN_PYTHON_VARIABLE( NEGATIVE_FACE_PRESSURE )
    // KRATOS_REGISTER_IN_PYTHON_VARIABLE( POSITIVE_FACE_PRESSURE )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CONSTITUTIVE_LAW_NO_INITIALIZE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( INTERNAL_VARIABLES )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( REFERENCE_WATER_PRESSURE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LAGRANGE_SCALE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( WATER_PRESSURE_SCALE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DP_EPSILON )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( INSITU_STRESS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DP_ALPHA1 )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DP_K )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CALCULATE_INSITU_STRESS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( USE_NUMERICAL_TANGENT )
    //CONTACT_LINK_MASTER is defined in condition.h
    //  KRATOS_REGISTER_IN_PYTHON_VARIABLE(CONTACT_LINK_MASTER )
    //CONTACT_LINK_SLAVE is defined in condition.h
    //  KRATOS_REGISTER_IN_PYTHON_VARIABLE(CONTACT_LINK_SLAVE )
    //  KRATOS_REGISTER_IN_PYTHON_VARIABLE(MASTER_CONTACT_LOCAL_POINT )
    //  KRATOS_REGISTER_IN_PYTHON_VARIABLE(MASTER_CONTACT_CURRENT_LOCAL_POINT )
    //  KRATOS_REGISTER_IN_PYTHON_VARIABLE(MASTER_CONTACT_LAST_CURRENT_LOCAL_POINT )
    //  KRATOS_REGISTER_IN_PYTHON_VARIABLE(SLAVE_CONTACT_LOCAL_POINT )
    //  KRATOS_REGISTER_IN_PYTHON_VARIABLE(MASTER_CONTACT_GLOBAL_POINT )
    //  KRATOS_REGISTER_IN_PYTHON_VARIABLE(MASTER_CONTACT_CURRENT_GLOBAL_POINT )
    //  KRATOS_REGISTER_IN_PYTHON_VARIABLE(SLAVE_CONTACT_GLOBAL_POINT )
    //  KRATOS_REGISTER_IN_PYTHON_VARIABLE(CONTACT_RAMP )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PENALTY )
    //  KRATOS_REGISTER_IN_PYTHON_VARIABLE(INITIAL_PENALTY )
    //  KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXIMUM_PENALTY )
    //  KRATOS_REGISTER_IN_PYTHON_VARIABLE(RAMP_CRITERION )
    //  KRATOS_REGISTER_IN_PYTHON_VARIABLE(RAMP_FACTOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PENALTY_T )
    // KRATOS_REGISTER_IN_PYTHON_VARIABLE( INITIAL_PENALTY_T )
    //  KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAXIMUM_PENALTY_T )
    //  KRATOS_REGISTER_IN_PYTHON_VARIABLE(RAMP_CRITERION_T )
    //  KRATOS_REGISTER_IN_PYTHON_VARIABLE(RAMP_FACTOR_T )
    // KRATOS_REGISTER_IN_PYTHON_VARIABLE(FRICTION_COEFFICIENT )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LAMBDA )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( MIU )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LAMBDAS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LAMBDAS_T )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( GAPS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DELTA_LAMBDAS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DELTA_LAMBDAS_T )
    //  KRATOS_REGISTER_IN_PYTHON_VARIABLE(MAX_UZAWA_ITERATIONS)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CONTACT_SLAVE_INTEGRATION_POINT_INDEX )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CONTACT_LINK_M )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CONTACT_DOUBLE_CHECK )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( IS_CONTACT_MASTER )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( IS_CONTACT_SLAVE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CONSTRAINT_MATRIX )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CONSTRAINT_VECTOR )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( IS_BBAR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( IS_FBAR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( FBAR_MODE )

    //  KRATOS_REGISTER_IN_PYTHON_VARIABLE(K_CONTACT )
    //  KRATOS_REGISTER_IN_PYTHON_VARIABLE(K_CONTACT_T )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( STICK )
    // KRATOS_REGISTER_IN_PYTHON_VARIABLE( FIRST_TIME_STEP )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( QUASI_STATIC_ANALYSIS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( NORMAL_STRESS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( TANGENTIAL_STRESS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( NORMAL_CONTACT_STRESS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( TANGENTIAL_CONTACT_STRESS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CONTACT_STICK )


    KRATOS_REGISTER_IN_PYTHON_VARIABLE( WATER_PRESSURE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( WATER_PRESSURE_DT )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( WATER_PRESSURE_NULL )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( WATER_PRESSURE_NULL_DT )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( WATER_PRESSURE_NULL_ACCELERATION )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( WATER_PRESSURE_EINS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( WATER_PRESSURE_EINS_DT )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( WATER_PRESSURE_EINS_ACCELERATION )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( AIR_PRESSURE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( AIR_PRESSURE_DT )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( AIR_PRESSURE_ACCELERATION )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( AIR_PRESSURE_NULL )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( AIR_PRESSURE_NULL_DT )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( AIR_PRESSURE_NULL_ACCELERATION )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( AIR_PRESSURE_EINS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( AIR_PRESSURE_EINS_DT )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( AIR_PRESSURE_EINS_ACCELERATION )

    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( DISPLACEMENT_OLD )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( DISPLACEMENT_DT )
    //  KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(ACCELERATION)
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( DISPLACEMENT_NULL )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( DISPLACEMENT_NULL_DT )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( ACCELERATION_NULL )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( DISPLACEMENT_EINS )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( DISPLACEMENT_EINS_DT )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( ACCELERATION_EINS )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( FORCE_CM )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( MOMENTUM_CM )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( ELASTIC_BEDDING_STIFFNESS )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ACTIVATION_LEVEL )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( BASE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( HEIGHT )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( FC )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( FT )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CONCRETE_YOUNG_MODULUS_C )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CONCRETE_YOUNG_MODULUS_T )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( FRACTURE_ENERGY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CRUSHING_ENERGY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ELASTIC_ENERGY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PLASTIC_ENERGY )
    //KRATOS_REGISTER_IN_PYTHON_VARIABLE( KINETIC_ENERGY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( POTENCIAL_ENERGY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DEFORMATION_ENERGY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( VON_MISES_STRESS )
    // KRATOS_REGISTER_IN_PYTHON_VARIABLE   ( YIELD_STRESS)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PLASTIC_MODULUS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PLASTICITY_INDICATOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LAMNDA )   // Load factor
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DAMAGE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ORTHOTROPIC_ANGLE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( VOLUMEN_FRACTION )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( MAX_INTERNAL_FRICTION_ANGLE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DILATANCY_ANGLE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( IS_DISCRETE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( MAX_DILATANCY_ANGLE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( COHESION )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ISOTROPIC_ELASTIC_LIMIT )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ORTHOTROPIC_ELASTIC_LIMIT )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( VECTOR_DAMAGE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ORTHOTROPIC_YOUNG_MODULUS_2D )   // [E1 E2 G12]
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ORTHOTROPIC_POISSON_RATIO_2D )   // [v12 v21]
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( GREEN_LAGRANGE_PLASTIC_STRAIN_TENSOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ELASTIC_STRAIN_VECTOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PLASTIC_STRAIN_VECTOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( STRESS_TENSOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( STRAIN_TENSOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ELASTIC_STRAIN_TENSOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ELASTIC_STRAIN_TENSOR_OLD )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PLASTIC_STRAIN_TENSOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LEFT_STRETCH_TENSOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( RIGHT_STRETCH_TENSOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CURRENT_STRAIN_VECTOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CURRENT_DEFORMATION_GRADIENT )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CURRENT_DEFORMATION_GRADIENT_DETERMINANT )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( INTEGRATION_POINT_STRAIN_VECTOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( EQUIVALENT_VOLUMETRIC_ELASTIC_STRAIN )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( EQUIVALENT_VOLUMETRIC_PLASTIC_STRAIN )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( EQUIVALENT_DEVIATORIC_ELASTIC_STRAIN )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( EQUIVALENT_DEVIATORIC_PLASTIC_STRAIN )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( EQUIVALENT_VOLUMETRIC_STRAIN )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( EQUIVALENT_DEVIATORIC_STRAIN )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( EQUIVALENT_STRAIN )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PRESTRAIN )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PRESTRESS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PRESTRESS_ZZ )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PRESTRESS_FACTOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( INITIAL_STRESS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DISIPATION )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ISOTROPIC_HARDENING_MODULUS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( KINEMATIC_HARDENING_MODULUS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ISOTROPIC_HARDENING_TYPE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( KINEMATIC_HARDENING_TYPE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DRUCKER_PRAGER_MATCHING_TYPE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( HARDENING_POINTS_ON_CURVE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( NODAL_STRESS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( NODAL_STRESS_VECTOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( NODAL_STRAIN )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( NODAL_STRAIN_VECTOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( NODAL_VALUES )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( NODAL_DAMAGE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( RAYLEIGH_DAMPING_ALPHA )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( RAYLEIGH_DAMPING_BETA )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( STABILISATION_FACTOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( SHEAR_MODULUS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( SHEAR_MODULUS_EVOLUTION )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( RECOVERY_STRESSES )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( THREED_STRESSES )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( THREED_PRESTRESS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( THREED_STRAIN )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DAMPING_RATIO )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( TENSILE_STRENGTH )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( SHEAR_STRENGTH )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( VISCOUS_DAMPING )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( YIELD_STATE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( YIELD_SURFACE )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( JOINT_FORCE_REACTION )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( JOINT_MOMENT_REACTION )
    //KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( INTERNAL_FORCE ) /already done in kratos kernel

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LAGRANGE_MULTIPLIER )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LAGRANGE_MULTIPLIER_INDEX )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( HAS_STRAIN_AT_NODE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( HAS_STRESSES_AT_NODE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( HAS_NODAL_ERROR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( FORCE_EQUAL_ORDER_INTERPOLATION )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( NODAL_ERROR_1 )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DUMMY_DOF )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( PRESCRIBED_DELTA_DISPLACEMENT )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( PRESCRIBED_DISPLACEMENT )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( INITIAL_DISPLACEMENT )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( LINE_LOAD )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( OVERCONSOLIDATION_RATIO )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PRECONSOLIDATION_PRESSURE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PRECONSOLIDATION_PRESSURE_DEF )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PRECONSOLIDATION_PRESSURE_MIN )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CSL_SLOPE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( VOID_RATIO )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( SPACING_RATIO )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( VIRGIN_COMPRESSION_INDEX )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( SWELL_INDEX )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ASSOCIATIVITY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( SHAPE_PARAMETER )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( YOUNG_MODULUS_0 )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( YOUNG_MODULUS_MIN )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PENALIZATION_FACTOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( MATERIAL_DENSITY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( GEOMETRICAL_DOMAIN_SIZE )
    // KRATOS_REGISTER_IN_PYTHON_VARIABLE( JACOBIAN_0 )
//    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ASSOCIATED_NODE )
//    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ASSOCIATED_ELEMENT )
//    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ASSOCIATED_CONDITION )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PRINCIPAL_STRESS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PRINCIPAL_STRAIN )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( STRESS_LIKE_INTERNAL_VARIABLES )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( STRAIN_LIKE_INTERNAL_VARIABLES )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PRIMARY_HYDRATION_TIME )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PRIMARY_HYDRATION_TIME_GRADIENT )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( STIFFNESS_RATIO )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( IS_MARKED_FOR_REACTION )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( EXTRAPOLATION_FACTOR_1 )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( EXTRAPOLATION_FACTOR_2 )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( FIX_POROSITY )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( QUAD_POINT_STATUS )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( L2_ERROR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( H1_ERROR )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ROTATIONAL_STIFFNESS )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( RATE_SENSITIVITY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LOCAL_ERROR_TOLERANCE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( REFERENCE_STRAIN_RATE )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PLASTIC_MODE )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( TAYLOR_QUINNEY_FACTOR )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PERTURBATION_FACTOR )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( HARDENING_LAW )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ISOTROPIC_HARDENING_LAW )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( KINEMATIC_HARDENING_LAW )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( INITIAL_DAMAGE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( FIX_DAMAGE )

}

}  // namespace Python.

}  // namespace Kratos.

#endif // KRATOS_PYTHON defined
