//    |  /           | 
//    ' /   __| _` | __|  _ \   __| 
//    . \  |   (   | |   (   |\__ \.
//   _|\_\_|  \__,_|\__|\___/ ____/ 
//                   Multi-Physics  
//
//  License:		 BSD License 
//					 Kratos default license: kratos/license.txt
//
//  Main authors:    Pooyan Dadvand
//











#if !defined(KRATOS_LEGACY_STRUCTURAL_APP_VARS_H_INCLUDED )
#define  KRATOS_LEGACY_STRUCTURAL_APP_VARS_H_INCLUDED



// System includes
#include <string>
#include <iostream>

// External includes


// Project includes
#include "includes/define.h"
#include "containers/variable.h"
#include "includes/ublas_interface.h"
#include "containers/array_1d.h"


namespace Kratos
{
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, bool, IS_INACTIVE )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, int, IS_JACK_LINK )

    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, LAMBDA_OLD )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, LAMBDA_NULL )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, LAMBDA_EINS )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, LAMBDA_DT )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, LAMBDA_NULL_DT )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, LAMBDA_EINS_DT )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, LAMBDA_DT2 )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, LAMBDA_NULL_DT2 )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, LAMBDA_EINS_DT2 )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, Matrix, LAMBDAS_T )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, Matrix, DELTA_LAMBDAS_T )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, Matrix, CONTACT_LINK_M )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, Matrix, AUXILIARY_MATRIX_1 )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, Matrix, ELASTIC_LEFT_CAUCHY_GREEN_OLD )

    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( STRUCTURAL_APPLICATION, DISPLACEMENT_OLD )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( STRUCTURAL_APPLICATION, DISPLACEMENT_DT )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( STRUCTURAL_APPLICATION, DISPLACEMENT_NULL )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( STRUCTURAL_APPLICATION, DISPLACEMENT_NULL_DT )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( STRUCTURAL_APPLICATION, ACCELERATION_NULL )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( STRUCTURAL_APPLICATION, DISPLACEMENT_EINS )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( STRUCTURAL_APPLICATION, DISPLACEMENT_EINS_DT )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( STRUCTURAL_APPLICATION, ACCELERATION_EINS )

    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( STRUCTURAL_APPLICATION, ROTATION_OLD )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( STRUCTURAL_APPLICATION, ROTATION_DT )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( STRUCTURAL_APPLICATION, ROTATION_NULL )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( STRUCTURAL_APPLICATION, ROTATION_NULL_DT )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( STRUCTURAL_APPLICATION, ANGULAR_ACCELERATION_NULL )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( STRUCTURAL_APPLICATION, ROTATION_EINS )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( STRUCTURAL_APPLICATION, ROTATION_EINS_DT )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( STRUCTURAL_APPLICATION, ANGULAR_ACCELERATION_EINS )

    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, Vector, PENALTY_T )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, INITIAL_PENALTY_T )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, Vector, LAMBDAS )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, Vector, GAPS )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, Vector, DELTA_LAMBDAS )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, Vector, STICK )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, CONTACT_STICK )

    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, bool, USE_DISTRIBUTED_PROPERTIES )

    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, int, CONTACT_RAMP )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, int, CONTACT_SLAVE_INTEGRATION_POINT_INDEX )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, int, CONTACT_DOUBLE_CHECK )
//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, int, FIRST_TIME_STEP )
//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, int, QUASI_STATIC_ANALYSIS )

    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, int, INTEGRATION_ORDER )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, INTEGRATION_WEIGHT )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( STRUCTURAL_APPLICATION,INTEGRATION_POINT_GLOBAL)
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( STRUCTURAL_APPLICATION,INTEGRATION_POINT_GLOBAL_IN_REFERENCE_CONFIGURATION)
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( STRUCTURAL_APPLICATION,INTEGRATION_POINT_GLOBAL_IN_CURRENT_CONFIGURATION)
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( STRUCTURAL_APPLICATION,INTEGRATION_POINT_LOCAL)

//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, int, OSS_SWITCH )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, int, WRINKLING_APPROACH )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, int, CALCULATE_INSITU_STRESS )
//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, int, PERIODIC_PAIR_INDEX )
//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, int, STATIONARY )

//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, int, PARTITION_MASK )

//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, FACE_HEAT_FLUX )

//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, NODAL_VOLUME )

    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, PRESSURE_DT )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, WATER_PRESSURE_DT )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, WATER_PRESSURE_ACCELERATION )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, WATER_PRESSURE_NULL )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, WATER_PRESSURE_NULL_DT )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, WATER_PRESSURE_NULL_ACCELERATION )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, WATER_PRESSURE_EINS )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, WATER_PRESSURE_EINS_DT )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, WATER_PRESSURE_EINS_ACCELERATION )

    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, AIR_PRESSURE_DT )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, AIR_PRESSURE_ACCELERATION )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, AIR_PRESSURE_NULL )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, AIR_PRESSURE_NULL_DT )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, AIR_PRESSURE_NULL_ACCELERATION )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, AIR_PRESSURE_EINS )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, AIR_PRESSURE_EINS_DT )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, AIR_PRESSURE_EINS_ACCELERATION )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, SUCTION )
//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, FLAG_VARIABLE )

//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, DP_EPSILON )
//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, DP_ALPHA1 )
//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, DP_K )

//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, EQ_STRAIN_RATE )
//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, RHS_WATER )
//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, RHS_AIR )

    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, PERMEABILITY_28_DAYS )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, PERMEABILITY_1_DAY )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, PERMEABILITY_TRANSITION )

    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, TEMPERATURE_DT )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, TEMPERATURE_DT_DT )
//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, TEMPERATURE_OLD_IT )
//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, EFFECTIVE_VISCOSITY )
//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, KINEMATIC_VISCOSITY)
//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, DYNAMIC_VISCOSITY)
//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, WEIGHT_FATHER_NODES )

    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, int, PARENT_ELEMENT_ID )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, int, INTEGRATION_POINT_INDEX )

    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, int, IS_CONTACT_MASTER )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, int, IS_CONTACT_SLAVE )
//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, IS_BOUNDARY )
//    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, IS_VISITED )

    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, LAGRANGE_MULTIPLIER_CONSTRAINT )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, double, LAGRANGE_MULTIPLIER_CONSTRAINT_REACTION )

    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, int, IS_SHAPE_FUNCTION_REQUIRED )
    KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_APPLICATION, int, RESET_CONFIGURATION )

}  // namespace Kratos.

#undef  KRATOS_EXPORT_MACRO
#define KRATOS_EXPORT_MACRO KRATOS_NO_EXPORT

#endif // KRATOS_LEGACY_STRUCTURAL_APP_VARS_H_INCLUDED  defined

