//    |  /           | 
//    ' /   __| _` | __|  _ \   __| 
//    . \  |   (   | |   (   |\__ \.
//   _|\_\_|  \__,_|\__|\___/ ____/ 
//                   Multi-Physics  
//
//  License:		 BSD License 
//					 Kratos default license: kratos/license.txt
//
//  Main authors:    Riccardo Rossi
//












// System includes
#include <string>
#include <iostream>
#include <vector>

// External includes

// Project includes
#include "includes/define.h"
#include "legacy_structural_app_vars.h"


namespace Kratos
{
    KRATOS_CREATE_VARIABLE( bool, IS_INACTIVE )
    KRATOS_CREATE_VARIABLE( int, IS_JACK_LINK )

    KRATOS_CREATE_VARIABLE( double, LAMBDA_OLD )
    KRATOS_CREATE_VARIABLE( double, LAMBDA_NULL )
    KRATOS_CREATE_VARIABLE( double, LAMBDA_EINS )
    KRATOS_CREATE_VARIABLE( double, LAMBDA_DT )
    KRATOS_CREATE_VARIABLE( double, LAMBDA_NULL_DT )
    KRATOS_CREATE_VARIABLE( double, LAMBDA_EINS_DT )
    KRATOS_CREATE_VARIABLE( double, LAMBDA_DT2 )
    KRATOS_CREATE_VARIABLE( double, LAMBDA_NULL_DT2 )
    KRATOS_CREATE_VARIABLE( double, LAMBDA_EINS_DT2 )
    KRATOS_CREATE_VARIABLE( Matrix, LAMBDAS_T )
    KRATOS_CREATE_VARIABLE( Matrix, DELTA_LAMBDAS_T )
    KRATOS_CREATE_VARIABLE( Matrix, CONTACT_LINK_M )
    KRATOS_CREATE_VARIABLE( Matrix, AUXILIARY_MATRIX_1 )
    KRATOS_CREATE_VARIABLE( Matrix, ELASTIC_LEFT_CAUCHY_GREEN_OLD )

    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( DISPLACEMENT_OLD )
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( DISPLACEMENT_DT )
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( DISPLACEMENT_NULL )
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( DISPLACEMENT_NULL_DT )
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( ACCELERATION_NULL )
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( DISPLACEMENT_EINS )
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( DISPLACEMENT_EINS_DT )
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( ACCELERATION_EINS )

    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( ROTATION_OLD )
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( ROTATION_DT )
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( ROTATION_NULL )
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( ROTATION_NULL_DT )
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( ANGULAR_ACCELERATION_NULL )
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( ROTATION_EINS )
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( ROTATION_EINS_DT )
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS( ANGULAR_ACCELERATION_EINS )

    KRATOS_CREATE_VARIABLE( Vector, PENALTY_T )
    KRATOS_CREATE_VARIABLE( double, INITIAL_PENALTY_T )
    KRATOS_CREATE_VARIABLE( Vector, LAMBDAS )
    KRATOS_CREATE_VARIABLE( Vector, GAPS )
    KRATOS_CREATE_VARIABLE( Vector, DELTA_LAMBDAS )
    KRATOS_CREATE_VARIABLE( Vector, STICK )
    KRATOS_CREATE_VARIABLE( double, CONTACT_STICK )

    KRATOS_CREATE_VARIABLE( bool, USE_DISTRIBUTED_PROPERTIES )

    KRATOS_CREATE_VARIABLE( int, CONTACT_RAMP )
    KRATOS_CREATE_VARIABLE( int, CONTACT_SLAVE_INTEGRATION_POINT_INDEX )
    KRATOS_CREATE_VARIABLE( int, CONTACT_DOUBLE_CHECK )
//    KRATOS_CREATE_VARIABLE( int, FIRST_TIME_STEP )
//    KRATOS_CREATE_VARIABLE( int, QUASI_STATIC_ANALYSIS )

    KRATOS_CREATE_VARIABLE( int, INTEGRATION_ORDER )
    KRATOS_CREATE_VARIABLE( double, INTEGRATION_WEIGHT )
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(INTEGRATION_POINT_GLOBAL)
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(INTEGRATION_POINT_GLOBAL_IN_REFERENCE_CONFIGURATION)
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(INTEGRATION_POINT_GLOBAL_IN_CURRENT_CONFIGURATION)
    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(INTEGRATION_POINT_LOCAL)

//    KRATOS_CREATE_VARIABLE( int, OSS_SWITCH )
    KRATOS_CREATE_VARIABLE( int, WRINKLING_APPROACH )
    KRATOS_CREATE_VARIABLE( int, CALCULATE_INSITU_STRESS )
//    KRATOS_CREATE_VARIABLE( int, PERIODIC_PAIR_INDEX )
//    KRATOS_CREATE_VARIABLE( int, STATIONARY )

//    KRATOS_CREATE_VARIABLE( int, PARTITION_MASK )

//    KRATOS_CREATE_VARIABLE( double, FACE_HEAT_FLUX )

//    KRATOS_CREATE_VARIABLE( double, NODAL_VOLUME )

    KRATOS_CREATE_VARIABLE( double, PRESSURE_DT )
    KRATOS_CREATE_VARIABLE( double, WATER_PRESSURE_DT )
    KRATOS_CREATE_VARIABLE( double, WATER_PRESSURE_ACCELERATION )
    KRATOS_CREATE_VARIABLE( double, WATER_PRESSURE_NULL )
    KRATOS_CREATE_VARIABLE( double, WATER_PRESSURE_NULL_DT )
    KRATOS_CREATE_VARIABLE( double, WATER_PRESSURE_NULL_ACCELERATION )
    KRATOS_CREATE_VARIABLE( double, WATER_PRESSURE_EINS )
    KRATOS_CREATE_VARIABLE( double, WATER_PRESSURE_EINS_DT )
    KRATOS_CREATE_VARIABLE( double, WATER_PRESSURE_EINS_ACCELERATION )

    KRATOS_CREATE_VARIABLE( double, AIR_PRESSURE_DT )
    KRATOS_CREATE_VARIABLE( double, AIR_PRESSURE_ACCELERATION )
    KRATOS_CREATE_VARIABLE( double, AIR_PRESSURE_NULL )
    KRATOS_CREATE_VARIABLE( double, AIR_PRESSURE_NULL_DT )
    KRATOS_CREATE_VARIABLE( double, AIR_PRESSURE_NULL_ACCELERATION )
    KRATOS_CREATE_VARIABLE( double, AIR_PRESSURE_EINS )
    KRATOS_CREATE_VARIABLE( double, AIR_PRESSURE_EINS_DT )
    KRATOS_CREATE_VARIABLE( double, AIR_PRESSURE_EINS_ACCELERATION )
    KRATOS_CREATE_VARIABLE( double, SUCTION )
//    KRATOS_CREATE_VARIABLE( double, FLAG_VARIABLE )

//    KRATOS_CREATE_VARIABLE( double, DP_EPSILON )
//    KRATOS_CREATE_VARIABLE( double, DP_ALPHA1 )
//    KRATOS_CREATE_VARIABLE( double, DP_K )

//    KRATOS_CREATE_VARIABLE( double, EQ_STRAIN_RATE )
//    KRATOS_CREATE_VARIABLE( double, RHS_WATER )
//    KRATOS_CREATE_VARIABLE( double, RHS_AIR )

    KRATOS_CREATE_VARIABLE( double, PERMEABILITY_28_DAYS )
    KRATOS_CREATE_VARIABLE( double, PERMEABILITY_1_DAY )
    KRATOS_CREATE_VARIABLE( double, PERMEABILITY_TRANSITION )

    KRATOS_CREATE_VARIABLE( double, TEMPERATURE_DT )
    KRATOS_CREATE_VARIABLE( double, TEMPERATURE_DT_DT )
//    KRATOS_CREATE_VARIABLE( double, TEMPERATURE_OLD_IT )
//    KRATOS_CREATE_VARIABLE( double, EFFECTIVE_VISCOSITY )
//    KRATOS_CREATE_VARIABLE( double, KINEMATIC_VISCOSITY)
//    KRATOS_CREATE_VARIABLE( double, DYNAMIC_VISCOSITY)
//    KRATOS_CREATE_VARIABLE( double, WEIGHT_FATHER_NODES )

    KRATOS_CREATE_VARIABLE( int, PARENT_ELEMENT_ID )
    KRATOS_CREATE_VARIABLE( int, INTEGRATION_POINT_INDEX )

    KRATOS_CREATE_VARIABLE( int, IS_CONTACT_MASTER )
    KRATOS_CREATE_VARIABLE( int, IS_CONTACT_SLAVE )
//    KRATOS_CREATE_VARIABLE( double, IS_BOUNDARY )
//    KRATOS_CREATE_VARIABLE( double, IS_VISITED )

    KRATOS_CREATE_VARIABLE( double, LAGRANGE_MULTIPLIER_CONSTRAINT )
    KRATOS_CREATE_VARIABLE( double, LAGRANGE_MULTIPLIER_CONSTRAINT_REACTION )

    KRATOS_CREATE_VARIABLE( int, IS_SHAPE_FUNCTION_REQUIRED )
    KRATOS_CREATE_VARIABLE( int, RESET_CONFIGURATION )

}  // namespace Kratos.

// This CREATE must be HERE
#undef DKRATOS_EXPORT_INTERFACE_2



